-- Table: public.departments

CREATE TABLE IF NOT EXISTS public.departments
(
    department_id integer GENERATED BY DEFAULT AS IDENTITY,
    department_name varchar(100) NOT NULL,

    CONSTRAINT departments_pkey
        PRIMARY KEY (department_id),

    CONSTRAINT departments_department_name_key
        UNIQUE (department_name)
);

-- Table: public.employment_status

CREATE TABLE IF NOT EXISTS public.employment_status
(
    employment_status_id integer GENERATED BY DEFAULT AS IDENTITY,
    employment_status_name varchar(50) NOT NULL,

    CONSTRAINT employment_status_pkey
        PRIMARY KEY (employment_status_id),

    CONSTRAINT employment_status_employment_status_name_key
        UNIQUE (employment_status_name)
);

-- Table: public.employment_types

CREATE TABLE IF NOT EXISTS public.employment_types
(
    employment_type_id integer GENERATED BY DEFAULT AS IDENTITY,
    employment_type_name varchar(50) NOT NULL,

    CONSTRAINT employment_types_pkey
        PRIMARY KEY (employment_type_id),

    CONSTRAINT employment_types_employment_type_name_key
        UNIQUE (employment_type_name)
);

-- Table: public.genders

CREATE TABLE IF NOT EXISTS public.genders
(
    gender_id integer GENERATED BY DEFAULT AS IDENTITY,
    gender_name varchar(50) NOT NULL,

    CONSTRAINT genders_pkey
        PRIMARY KEY (gender_id),

    CONSTRAINT genders_gender_name_key
        UNIQUE (gender_name)
);

-- Table: public.job_title

CREATE TABLE IF NOT EXISTS public.job_title
(
    job_title_id integer GENERATED BY DEFAULT AS IDENTITY,
    job_title_name varchar(150) NOT NULL,

    CONSTRAINT job_title_pkey
        PRIMARY KEY (job_title_id),

    CONSTRAINT job_title_job_title_name_key
        UNIQUE (job_title_name)
);

-- Table: public.marital_status

CREATE TABLE IF NOT EXISTS public.marital_status
(
    marital_status_id integer GENERATED BY DEFAULT AS IDENTITY,
    marital_status_name varchar(50) NOT NULL,

    CONSTRAINT marital_status_pkey
        PRIMARY KEY (marital_status_id),

    CONSTRAINT marital_status_marital_status_name_key
        UNIQUE (marital_status_name)
);

-- Table: public.document_type

CREATE TABLE IF NOT EXISTS public.document_type
(
    document_type_id integer GENERATED BY DEFAULT AS IDENTITY,
    document_type_name varchar(50) NOT NULL,

    CONSTRAINT document_type_pkey
        PRIMARY KEY (document_type_id),

    CONSTRAINT document_type_document_type_name_key
        UNIQUE (document_type_name)
);

-- Table: public.document_status

CREATE TABLE IF NOT EXISTS public.document_status
(
    document_status_id integer GENERATED BY DEFAULT AS IDENTITY,
    document_status_name varchar(50) NOT NULL,

    CONSTRAINT document_status_pkey
        PRIMARY KEY (document_status_id),

    CONSTRAINT document_status_document_status_name_key
        UNIQUE (document_status_name)
);

-- Table: public.employees

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id character varying(20) NOT NULL,
    first_name character varying(100) NOT NULL,
    middle_name character varying(100),
    last_name character varying(100) NOT NULL,
    gender character varying(30),
    date_of_birth date,
    phone_number character varying(30),
    marital_status character varying(30),
    email character varying(255),
    company_email character varying(255),
    residential_address text,
    date_of_joining date NOT NULL,
    department character varying(100),
    job_title character varying(150),
    employment_type character varying(50),
    employment_status character varying(50) NOT NULL,
    date_of_exit date,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    state character varying(100),
    gender_id integer,
    marital_status_id integer,
    department_id integer,
    employment_type_id integer,
    employment_status_id integer,
    job_title_id integer,

    CONSTRAINT employees_pkey PRIMARY KEY (employee_id),

    CONSTRAINT employees_company_email_unique
        UNIQUE (company_email),

    CONSTRAINT employees_email_unique
        UNIQUE (email),

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id),

    CONSTRAINT fk_employee_employment_status
        FOREIGN KEY (employment_status_id)
        REFERENCES public.employment_status (employment_status_id),

    CONSTRAINT fk_employee_employment_type
        FOREIGN KEY (employment_type_id)
        REFERENCES public.employment_types (employment_type_id),

    CONSTRAINT fk_employee_gender
        FOREIGN KEY (gender_id)
        REFERENCES public.genders (gender_id),

    CONSTRAINT fk_employee_job_title
        FOREIGN KEY (job_title_id)
        REFERENCES public.job_title (job_title_id),

    CONSTRAINT fk_employee_marital_status
        FOREIGN KEY (marital_status_id)
        REFERENCES public.marital_status (marital_status_id),

    CONSTRAINT chk_employee_dates
        CHECK (date_of_exit IS NULL OR date_of_exit >= date_of_joining),

    CONSTRAINT chk_employee_birth_date
        CHECK (date_of_birth IS NULL OR date_of_birth < date_of_joining)
);

-- Table: public.identification

CREATE TABLE IF NOT EXISTS public.identification
(
    identification_id integer GENERATED BY DEFAULT AS IDENTITY,
    employee_id varchar(20) NOT NULL,
    nin varchar(20),
    other_id_type varchar(20),
    other_id_number varchar(100),

    CONSTRAINT identification_pkey
        PRIMARY KEY (identification_id),

    CONSTRAINT identification_nin_unique
        UNIQUE (nin),

    CONSTRAINT fk_identification_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
);

-- Table: public.bank_details

CREATE TABLE IF NOT EXISTS public.bank_details
(
    bank_detail_id integer GENERATED BY DEFAULT AS IDENTITY,
    employee_id varchar(20) NOT NULL,
    bank_name varchar(100),
    account_name varchar(50),
    account_number varchar(20),

    CONSTRAINT bank_details_pkey
        PRIMARY KEY (bank_detail_id),

    CONSTRAINT uq_bank_details_employee
        UNIQUE (employee_id),

    CONSTRAINT fk_bank_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id)
);

-- Table: public.documents

CREATE TABLE IF NOT EXISTS public.documents
(
    document_id integer GENERATED BY DEFAULT AS IDENTITY,
    employee_id varchar(20) NOT NULL,
    document_type varchar(100) NOT NULL,
    document_status varchar(50),
    date_added date,
    expiry_date date,
    file_location text,
    document_type_id integer,
    document_status_id integer,

    CONSTRAINT documents_pkey
        PRIMARY KEY (document_id),

    CONSTRAINT fk_documents_document_status
        FOREIGN KEY (document_status_id)
        REFERENCES public.document_status (document_status_id),

    CONSTRAINT fk_documents_document_type
        FOREIGN KEY (document_type_id)
        REFERENCES public.document_type (document_type_id),

    CONSTRAINT fk_documents_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id),

    CONSTRAINT chk_document_dates
        CHECK (
            expiry_date IS NULL
            OR date_added IS NULL
            OR expiry_date >= date_added
        )
);

-- Table: public.employment_history

CREATE TABLE IF NOT EXISTS public.employment_history
(
    employment_history_id integer GENERATED BY DEFAULT AS IDENTITY,
    employee_id varchar(20) NOT NULL,
    department varchar(100),
    job_title varchar(150),
    start_date date NOT NULL,
    end_date date,
    reason_for_change varchar(100),
    department_id integer,
    job_title_id integer,

    CONSTRAINT employment_history_pkey
        PRIMARY KEY (employment_history_id),

    CONSTRAINT fk_history_department
        FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id),

    CONSTRAINT fk_history_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id),

    CONSTRAINT fk_history_job_title
        FOREIGN KEY (job_title_id)
        REFERENCES public.job_title (job_title_id),

    CONSTRAINT chk_history_dates
        CHECK (end_date IS NULL OR end_date >= start_date)
);
